# Generated by Django 5.0.6 on 2024-07-18 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(max_length=64)),
                ('model_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('updates', models.CharField(max_length=1064)),
                ('updated_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('location_address1', models.CharField(max_length=255, null=True)),
                ('location_address2', models.CharField(max_length=255, null=True)),
                ('location_city', models.CharField(max_length=255, null=True)),
                ('location_province', models.CharField(max_length=255, null=True)),
                ('location_zip_code', models.CharField(max_length=255, null=True)),
                ('borehole_quantity', models.IntegerField()),
                ('borehole_depth_meters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField()),
                ('status', models.CharField(default='ONGOING', max_length=64)),
                ('pe_pm', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField(verbose_name='Line No.')),
                ('machine_id', models.CharField(max_length=255, verbose_name='Machine ID')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('capacity_code', models.CharField(max_length=255, verbose_name='Capacity Code')),
                ('year', models.IntegerField(null=True, verbose_name='Year')),
                ('tripod', models.IntegerField(null=True, verbose_name='Tripod')),
                ('water_pump', models.IntegerField(null=True, verbose_name='Water Pump')),
                ('toolbox', models.IntegerField(null=True, verbose_name='Toolbox')),
                ('pipe_wrench_pair', models.IntegerField(null=True, verbose_name='Pipe Wrench Pair')),
                ('casing', models.IntegerField(null=True, verbose_name='Casing')),
                ('rod', models.IntegerField(null=True, verbose_name='Rod')),
                ('reamer', models.IntegerField(null=True, verbose_name='Reamer')),
                ('diamond_bit', models.IntegerField(null=True, verbose_name='Diamond Bit')),
                ('spt_hammer', models.IntegerField(null=True, verbose_name='SPT Hammer')),
                ('spt_sampler', models.IntegerField(null=True, verbose_name='SPT Sampler')),
                ('fire_ext', models.IntegerField(null=True, verbose_name='Fire Ext')),
                ('cm_tank', models.IntegerField(null=True, verbose_name='CM Tank')),
                ('l_tank', models.IntegerField(null=True, verbose_name='L Tank')),
                ('fuel_tank', models.IntegerField(null=True, verbose_name='Fuel Tank')),
                ('maintenance_date', models.DateField(verbose_name='Maintenance Date')),
                ('maintenance_due_date', models.DateField(null=True, verbose_name='Maintenance Due Date')),
                ('last_assignment_date', models.DateField(null=True, verbose_name='Last Assignment Date')),
                ('mobilization_date', models.DateField(null=True, verbose_name='Date of Mobilization')),
                ('demobilization_date', models.DateField(null=True, verbose_name='Date of Demobilization')),
                ('delivered_by_fname', models.CharField(default='', max_length=255, null=True)),
                ('delivered_by_lname', models.CharField(default='', max_length=255, null=True)),
                ('received_by_fname', models.CharField(default='', max_length=255, null=True)),
                ('received_by_lname', models.CharField(default='', max_length=255, null=True)),
                ('operator_fname', models.CharField(default='', max_length=255, null=True)),
                ('operator_lname', models.CharField(default='', max_length=255, null=True)),
                ('status', models.CharField(default='AVAILABLE', max_length=64, verbose_name='Status')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='core.project')),
            ],
        ),
    ]
