# Generated by Django 5.0.6 on 2024-11-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default='', max_length=255, verbose_name='Position'),
        ),
    ]
