# Generated by Django 5.0.6 on 2024-11-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employee_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_ea', models.IntegerField(verbose_name='Site EA')),
                ('smart_site_id', models.CharField(max_length=255, verbose_name='Site ID')),
                ('name', models.CharField(max_length=255, verbose_name='Site ID')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('municipality', models.CharField(max_length=255, verbose_name='Municipality')),
                ('province', models.CharField(max_length=255, verbose_name='Province')),
                ('classification', models.CharField(max_length=255, verbose_name='Classification')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
            ],
        ),
    ]
